#
# saarti algorithm configuration
#

# replanning rate
dt: 0.1

# Reference mode, 
# 0: minimize s
# 1: maximize s
ref_mode: 1 

# Algorithm mode, 
# 0: RTI
# 1: SAA-RTI 
algo_mode: 0

# Adaptation mode,
# 0: takes mu estimate from pathlocal struct and computes normal forces from pitch dynamics
# 1: static mu estimate from param and static tire force constraints
adaptive_mode: 1 
mu_static: 0.9

# rollout config
Ntrajs_rollout: 24 # default 24

# optimization config
Wx:  [100.0, 1.0, 1.0, 0.1, 0.1, 0.1]
WNx: [100.0, 1.0, 1.0, 0.1, 0.1, 0.1]
Wu: [0.1, 0.1, 0.1]
Wslack: 100000000


